name: Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubicloud-standard-4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
        # with:
          # components: rustfmt, clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: |
          cargo check --release    